config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  root 'home#index'

  resources :pages, only: :show
  resources :houses, only: [:index, :show, :update]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    # can :read, :all                   # allow everyone to read everything
    if user && user.admin?
      can :read, :all
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :dashboard                  # allow access to dashboard
      can :manage, :all
      can :access, :houses
    elsif user
      can :access, :houses
      can :update, :houses
      can :read, :houses
    end
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  validates :name, :description, :attachable_id, presence: true

  belongs_to :attachable, polymorphic: true

  has_attached_file :file_attachment
  validates_attachment :file_attachment,
		presence: true,
		content_type: { content_type: %w(image/jpeg image/jpg image/png image/gif application/pdf application/msword text/plain) },
		size: { in: 0..10.megabytes }
end

app/models/house.rb
class House < ActiveRecord::Base
  validates :name, :address1, :city, :state, :zip, :country, presence: true

  belongs_to :user
  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :units
  has_many :maintenances

  geocoded_by :address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

  has_attached_file :image, styles: { large: "1500x1000>", medium: "300x300>", thumb: "100x100>" }
  validates_attachment :image,
		presence: true,
		content_type: { content_type: %w(image/jpeg image/jpg image/png image/gif) },
		size: { in: 0..10.megabytes }

  def address
    "#{address1}, #{city} #{state} #{zip}"
  end
end

app/models/maintenance.rb
class Maintenance < ActiveRecord::Base
  extend Enumerize

  belongs_to :house

  validates :title, :category, :priority, :status, :description, :house_id, presence: true

  has_attached_file :image, styles: { large: "1500x1000>", medium: "300x300>", thumb: "100x100>" }
  validates_attachment :image,
		presence: true,
		content_type: { content_type: %w(image/jpeg image/jpg image/png image/gif) },
		size: { in: 0..10.megabytes }

  enumerize :category, in: [:home_improvement, :exterior, :interior], default: :home_improvement
  enumerize :priority, in: [:low, :normal, :high, :critical], default: :low
  enumerize :status, in: [:new, :in_progress, :resolved, :deferred, :archived], default: :new
end

app/models/page.rb
class Page < ActiveRecord::Base
  validates :name, :content, presence: true
  validates :name, uniqueness: true

  has_many :attachments, as: :attachable, dependent: :destroy
end

app/models/service_provider.rb
class ServiceProvider < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates :name, presence: true

  has_many :houses
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :house

  has_attached_file :lease
  validates_attachment :lease,
		presence: true,
		content_type: { content_type: %w(image/jpeg image/jpg image/png image/gif application/pdf application/msword text/plain) },
		size: { in: 0..10.megabytes }
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :houses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to main_app.root_url, :alert => exception.message }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.admin?
      @houses = House.all
    else
      @houses = House.where(user: current_user)
    end
  end

  def show
    @house = House.find(params[:id])
  end

  def update
    @house = House.find(params[:id])
    if @house.update_attributes(house_params)
      redirect_to(@house, :notice => 'Updated successfully.')
    else
      render :show
    end
  end

  private
    def house_params
      if current_user.admin?
        params.require(:house).permit(:admin_notes, :user_notes)
      else
        params.require(:house).permit(:user_notes)
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>Welcome to FFC Web Help</h1>
  </div>
</div>

<div class="row">
  <% Page.all.each do |page| %>
    <div class="col-md-3">
      <div class="portlet">
        <div class="portlet-heading">
            <h3 class="portlet-title text-dark">
                <%= page.name %>
            </h3>
            <div class="portlet-widgets">
                <a href="javascript:;" data-toggle="reload"><span class="glyphicon glyphicon-refresh"></span></a>
                <span class="divider"></span>
                <a data-toggle="collapse" data-parent="#accordion1" href="#bg-default"><span class="glyphicon glyphicon-minus"></span></a>
                <span class="divider"></span>
                <a href="#" data-toggle="remove"><span class="glyphicon glyphicon-remove"></span></a>
            </div>
            <div class="clearfix"></div>
        </div>
        <div id="bg-default" class="panel-collapse collapse in">
            <div class="portlet-body">
                <%= page.intro.html_safe if page.intro %>
            </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/houses/index.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>Properties</h1>
  </div>
</div>

<div class="row">
  <% @houses.each do |house| %>
    <div class="col-md-4">
      <div class="profile-widget text-center" id="house-<%= house.id %>">
          <div class="bg-info bg-profile"></div>
          <%= image_tag house.image.url(:thumb), class: 'thumb-lg img-circle img-thumbnail', alt: "#{house.name}" %>
          <h3><%= house.name %></h3>
          <p><%= link_to "http://maps.google.com/?q=#{house.latitude},#{house.longitude}", target: '_blank' do %><i class="fa fa-map-marker"></i> <%= house.address1 %><% end %></p>
          <%= link_to 'View', house, class: 'btn btn-sm btn-purple m-t-20' %>
          <ul class="list-inline widget-list clearfix">
              <li class="col-md-4"><span><%= house.units.length %></span>Units</li>
              <li class="col-md-4"><span>2</span>Reminders</li>
              <li class="col-md-4"><span><%= house.maintenances.length %></span>Maintenances</li>
          </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/houses/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h1><%= @house.name %></h1>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="mini-stat clearfix">
      <span class="mini-stat-icon bg-pink"><i class="fa fa-user"></i></span>
      <div class="mini-stat-info text-right">
          <span class="counter"><%= @house.units.length %></span>
          Units
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="mini-stat clearfix">
      <span class="mini-stat-icon bg-info"><i class="fa fa-bell"></i></span>
      <div class="mini-stat-info text-right">
          <span class="counter">5</span>
          Reminders
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="mini-stat clearfix">
      <span class="mini-stat-icon bg-success"><i class="fa fa-wrench"></i></span>
      <div class="mini-stat-info text-right">
          <span class="counter"><%= @house.maintenances.length %></span>
          Maintenance
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading" style="background-image: none">
        <h3 class="panel-title">Units</h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div id="datatable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
              <div class="row">
                <div class="col-sm-12">
                  <table id="datatable" class="table table-striped table-bordered dataTable no-footer" role="grid" aria-describedby="datatable_info">
                    <thead>
                        <tr role="row">
                          <th class="sorting_asc" tabindex="0" aria-controls="datatable"
                            rowspan="1" colspan="1" style="width: 121px;" aria-sort="ascending"
                            aria-label="Name: activate to sort column descending">
                            Name
                          </th>
                          <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1"
                          aria-label="Position: activate to sort column ascending">
                            Rent
                          </th>
                          <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1"
                          aria-label="Office: activate to sort column ascending">
                            Start
                          </th>
                          <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1"
                          colspan="1" aria-label="Age: activate to sort column ascending">
                            End
                          </th>
                          <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1"
                          aria-label="Start date: activate to sort column ascending">
                            Lease
                          </th>
                        </tr>
                    </thead>
                    <tbody>
                      <% @house.units.each_with_index do |unit, i| %>
                        <tr role="row" class="<%= i % 2 == 0 ? 'even' : 'odd' %>">
                          <td><%= unit.name %></td>
                          <td><%= number_to_currency(unit.rent) %></td>
                          <td><%= unit.lease_start.strftime("%m/%d/%Y") %></td>
                          <td><%= unit.lease_end.strftime("%m/%d/%Y") %></td>
                          <td><%= link_to unit.lease.url(:original), target: '_blank' do %><i class="fa fa-file-text"></i><% end %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading" style="background-image: none">
        <h3 class="panel-title">Maintenances</h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div id="datatable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
              <div class="row">
                <div class="col-sm-12">
                  <table id="datatable" class="table table-striped table-bordered dataTable no-footer" role="grid" aria-describedby="datatable_info">
                    <thead>
                        <tr role="row">
                          <th class="sorting_asc" tabindex="0" aria-controls="datatable"
                            rowspan="1" colspan="1" style="width: 121px;" aria-sort="ascending"
                            aria-label="Name: activate to sort column descending">
                            Title
                          </th>
                          <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1"
                          aria-label="Position: activate to sort column ascending">
                            Priority
                          </th>
                          <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1"
                          aria-label="Office: activate to sort column ascending">
                            Status
                          </th>
                          <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1"
                          colspan="1" aria-label="Age: activate to sort column ascending">
                            Category
                          </th>
                          <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1"
                          aria-label="Start date: activate to sort column ascending">
                            Image
                          </th>
                        </tr>
                    </thead>
                    <tbody>
                      <% @house.maintenances.each_with_index do |maintenance, i| %>
                        <tr role="row" class="<%= i % 2 == 0 ? 'even' : 'odd' %>">
                          <td><%= maintenance.title %></td>
                          <td><span class="label label-purple"><%= maintenance.priority.text %></span></td>
                          <td><%= maintenance.status.text %></td>
                          <td><%=  maintenance.category.text %></td>
                          <td><%= link_to  maintenance.image.url(:large), target: '_blank' do %><i class="fa fa-file-image-o"></i><% end %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
-->
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-color panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Service Provider Notes</h3>
      </div>
      <div class="panel-body">
        <div class="col-md-12">
          <%= simple_form_for @house, html: { class: 'form-horizontal m-t-40' } do |f| %>
            <%= f.input :user_notes, label: false, placeholder: "Enter notes...", input_html: { class: 'form-control notes-area' } %>
            <div class="form-group">
                <button type="submit" class="btn btn-purple">Update</button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="panel panel-color panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Admin Notes</h3>
      </div>
      <div class="panel-body">
        <div class="col-md-12">
          <% if current_user.admin? %>
            <%= simple_form_for @house, html: { class: 'form-horizontal m-t-40' } do |f| %>
              <%= f.input :admin_notes, label: false, placeholder: "Enter notes...", input_html: { class: 'form-control notes-area' } %>
              <div class="form-group">
                  <button type="submit" class="btn btn-purple">Update</button>
              </div>
            <% end %>
          <% else %>
            <%= @house.admin_notes.html_safe %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
      $('.dataTable').DataTable();

      /* Counter Up */
      $('.counter').counterUp({
          delay: 100,
          time: 1200
      });

      $('.notes-area').wysihtml5({
	      "image": false, //Button to insert an image. Default true,
	      "color": false //Button to change color of font
      });
  });
</script>

app/views/layouts/_nav.html.erb
<header class="top-head container-fluid">
  <button type="button" class="navbar-toggle pull-left">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
  </button>

  <!-- Search -->
  <!--
  <form role="search" class="navbar-left app-search pull-left hidden-xs">
    <input placeholder="Search..." class="form-control" type="text">
    <a href=""><i class="fa fa-search"></i></a>
  </form>
-->

  <!-- Left navbar -->
  <nav class=" navbar-default" role="navigation">
      <ul class="nav navbar-nav hidden-xs">
          <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">Information <span class="caret"></span></a>
              <ul role="menu" class="dropdown-menu">
                <% Page.all.each do |page| %>
                  <li><%= link_to page.name, page_path(page) %></li>
                <% end %>
              </ul>
          </li>
          <!-- <li><a href="#">Files</a></li> -->
      </ul>

      <!-- Right navbar -->
      <ul class="nav navbar-nav navbar-right top-right-menu">
          <!-- mesages -->
          <li class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                  <i class="fa fa-envelope"></i>
                  <span class="badge badge-sm up bg-purple count">4</span>
              </a>
              <ul class="dropdown-menu extended fadeInUp animated nicescroll" tabindex="5001" style="overflow: hidden;">
                  <li>
                      <p>Messages</p>
                  </li>
                  <li>
                      <a href="#">
                          <span class="pull-left">
                            <%= image_tag 'avatar-2.jpg', class: 'img-circle thumb-sm m-r-15', alt: 'img' %>
                          </span>
                          <span class="block"><strong>John smith</strong></span>
                          <span class="media-body block">New tasks needs to be done<br><small class="text-muted">10 seconds ago</small></span>
                      </a>
                  </li>
                  <li>
                      <a href="#">
                          <span class="pull-left">
                              <%= image_tag 'avatar-3.jpg', class: 'img-circle thumb-sm m-r-15', alt: 'img' %>
                          </span>
                          <span class="block"><strong>John smith</strong></span>
                          <span class="media-body block">New tasks needs to be done<br><small class="text-muted">3 minutes ago</small></span>
                      </a>
                  </li>
                  <li>
                      <a href="#">
                          <span class="pull-left">
                            <%= image_tag 'avatar-4.jpg', class: 'img-circle thumb-sm m-r-15', alt: 'img' %>
                          </span>
                          <span class="block"><strong>John smith</strong></span>
                          <span class="media-body block">New tasks needs to be done<br><small class="text-muted">10 minutes ago</small></span>
                      </a>
                  </li>
                  <li>
                      <p><a href="inbox.html" class="text-right">See all Messages</a></p>
                  </li>
              </ul>
          </li>
          <!-- /messages -->
          <!-- Notification -->
          <li class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                  <i class="fa fa-bell"></i>
                  <span class="badge badge-sm up bg-pink count">3</span>
              </a>
              <ul class="dropdown-menu extended fadeInUp animated nicescroll" tabindex="5002" style="overflow: hidden;">
                  <li class="noti-header">
                      <p>Notifications</p>
                  </li>
                  <li>
                      <a href="#">
                          <span class="pull-left"><i class="fa fa-user-plus fa-2x text-info"></i></span>
                          <span>New user registered<br><small class="text-muted">5 minutes ago</small></span>
                      </a>
                  </li>
                  <li>
                      <a href="#">
                          <span class="pull-left"><i class="fa fa-diamond fa-2x text-primary"></i></span>
                          <span>Use animate.css<br><small class="text-muted">5 minutes ago</small></span>
                      </a>
                  </li>
                  <li>
                      <a href="#">
                          <span class="pull-left"><i class="fa fa-bell-o fa-2x text-danger"></i></span>
                          <span>Send project demo files to client<br><small class="text-muted">1 hour ago</small></span>
                      </a>
                  </li>

                  <li>
                      <p><a href="#" class="text-right">See all notifications</a></p>
                  </li>
              </ul>
          </li>
          <!-- /Notification -->

          <!-- user login dropdown start-->
          <% if current_user %>
            <li class="dropdown text-center">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <%= image_tag 'avatar-2.jpg', class: 'img-circle profile-img thumb-sm' %>
                    <span class="username"><%= current_user.name %> </span> <span class="caret"></span>
                </a>
                <ul class="dropdown-menu pro-menu fadeInUp animated" tabindex="5003" style="overflow: hidden; outline: none;">
                    <li><%= link_to edit_user_registration_path do %><i class="fa fa-briefcase"></i> Profile</a><% end %></li>
                    <% if current_user.admin? %>
                      <li><%= link_to rails_admin_path, target: '_blank' do %><i class="fa fa-cog"></i> Admin<% end %></li>
                    <% end %>
                    <li><%= link_to destroy_user_session_path, method: :delete do %><i class="fa fa-sign-out"></i> Log Out<% end %></li>
                </ul>
            </li>
          <% else %>
            <li class="text-center">
                <%= link_to 'Log In', new_user_session_path %>
            </li>
          <% end %>
          <!-- user login dropdown end -->
      </ul>
      <!-- End right navbar -->
  </nav>

  <div id="ascrail2000" class="nicescroll-rails" style="width: 7px; z-index: 3; cursor: default; position: absolute; top: 0px; left: 23px; height: 327px; display: none;"><div style="position: relative; top: 0px; float: right; width: 5px; height: 0px; background-color: rgb(157, 158, 165); border: 1px solid rgb(255, 255, 255); background-clip: padding-box; border-radius: 0px;"></div></div><div id="ascrail2000-hr" class="nicescroll-rails" style="height: 7px; z-index: 3; top: 320px; left: -250px; position: absolute; cursor: default; display: none;">
  <div style="position: relative; top: 0px; height: 5px; width: 0px; background-color: rgb(157, 158, 165); border: 1px solid rgb(255, 255, 255); background-clip: padding-box; border-radius: 0px;"></div></div><div id="ascrail2001" class="nicescroll-rails" style="width: 7px; z-index: 3; cursor: default; position: absolute; top: 0px; left: 23px; height: 267px; display: none;"><div style="position: relative; top: 0px; float: right; width: 5px; height: 0px; background-color: rgb(157, 158, 165); border: 1px solid rgb(255, 255, 255); background-clip: padding-box; border-radius: 0px;">
  </div>
  </div>
  <div id="ascrail2001-hr" class="nicescroll-rails" style="height: 7px; z-index: 3; top: 260px; left: -250px; position: absolute; cursor: default; display: none;">
    <div style="position: relative; top: 0px; height: 5px; width: 0px; background-color: rgb(157, 158, 165); border: 1px solid rgb(255, 255, 255); background-clip: padding-box; border-radius: 0px;">
    </div>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<!-- Aside Start-->
<aside class="left-panel">

    <!-- brand -->
    <div class="logo">
        <%= link_to '/', class: 'logo-expanded' do %>
            <i class="fa fa-pagelines"></i>
            <span class="nav-label">N+P</span>
        <% end %>
    </div>
    <!-- / brand -->

    <!-- Navbar Start -->
    <nav class="navigation">
        <ul class="list-unstyled">
            <li class="<%= current_page?(root_path) ? 'active' : '' %>"><%= link_to root_path do %><span class="nav-label"><i class="fa fa-tachometer"></i>Dashboard</span><% end %></li>
            <% if current_user %>
              <li class="<%= current_page?(houses_path) ? 'active' : '' %>"><%= link_to houses_path do %><span class="nav-label"><i class="fa fa-home"></i>Properties</span><% end %></li>
            <% end %>
            <% Page.all.each do |page| %>
              <li class="<%= @page && @page.name == page.name ? 'active' : '' %>"><%= link_to page_path(page) do %><span class="nav-label"><i class="fa fa-<%= page.icon %>"></i><%= page.name %></span><% end %></li>
            <% end %>
        </ul>
    </nav>

</aside>
<!-- Aside Ends-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FfcWebForm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
</head>
<body>

  <%= render 'layouts/sidebar' %>

  <!--Main Content Start -->
        <section class="content">
            <!-- Header -->
            <%= render 'layouts/nav' %>
            <!-- Header Ends -->


            <!-- Page Content Start -->
            <!-- ================== -->

            <% flash.each do |name, msg| %>
              <% if msg.is_a?(String) %>
                <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <%= content_tag :div, msg, :id => "flash_#{name}" %>
                </div>
              <% end %>
            <% end %>

            <div class="wraper container-fluid">
                <%= yield %>
            </div>
            <!-- Page Content Ends -->
            <!-- ================== -->

            <!-- Footer Start -->
            <footer class="footer">
                <%= Date.today.year %> © Navarre + Pollowitz.
            </footer>
            <!-- Footer Ends -->


        </section>
        <!-- Main Content Ends -->
  </div>
</body>
</html>

app/views/pages/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="portlet">
      <div class="portlet-heading bg-inverse">
          <h3 class="portlet-title">
            <i class="fa fa-<%= @page.icon %>"></i> <%= @page.name %>
          </h3>
          <div class="portlet-widgets">
              <a href="javascript:;" data-toggle="reload"><span class="glyphicon glyphicon-refresh"></span></a>
              <span class="divider"></span>
              <a data-toggle="collapse" data-parent="#accordion1" href="#bg-default"><span class="glyphicon glyphicon-minus"></span></a>
              <span class="divider"></span>
              <a href="#" data-toggle="remove"><span class="glyphicon glyphicon-remove"></span></a>
          </div>
          <div class="clearfix"></div>
      </div>
      <div id="bg-default" class="panel-collapse collapse in">
          <div class="portlet-body">
              <%= @page.content.html_safe %>
          </div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <ul class="nav nav-tabs nav-justified">
      <li class="active">
          <a href="#attachments" data-toggle="tab" aria-expanded="true">
              <span class="visible-xs"><i class="fa fa-paperclip"></i></span>
              <span class="hidden-xs">Attachments</span>
          </a>
      </li>
      <li class="">
          <a href="#videos" data-toggle="tab" aria-expanded="false">
              <span class="visible-xs"><i class="fa fa-video-camera"></i></span>
              <span class="hidden-xs">Videos</span>
          </a>
      </li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="attachments">
        <% @page.attachments.each do |attachment| %>
          <p>
            <%= link_to attachment.name, attachment.file_attachment.url(:original) %>
          </p>
        <% end %>
      </div>
      <div class="tab-pane" id="videos">
          <p>Fulfilled direction use continual set him propriety continued. Saw met applauded favourite deficient engrossed concealed and her. Concluded boy perpetual old supposing. Farther related bed and passage comfort civilly. Dashwoods see frankness objection abilities the. As hastened oh produced prospect formerly up am. Placing forming nay looking old married few has. Margaret disposed add screened rendered six say his striking confined. </p>
          <p>When be draw drew ye. Defective in do recommend suffering. House it seven in spoil tiled court. Sister others marked fat missed did out use. Alteration possession dispatched collecting instrument travelling he or on. Snug give made at spot or late that mr. </p>
      </div>
    </div>
  </div>
</div>